{
    "openapi": "3.0.0",
    "info": {
        "title": "Order & Process Payment APIs",
        "contact": {},
        "version": "1.0",
        "description": "Comprehensive reference for integrating with Plural APIs."
    },
    "servers": [
        {
            "url": "https://api.pluralonline.com/api/v1/order",
            "variables": {}
        },
        {
            "url": "https://api-staging.pluralonline.com/api/v1/card/process",
            "variables": {}
        },
        {
            "url": "https://pluralqa.pinepg.in/api",
            "variables": {}
        },
        {
            "url": "https://test.pinepg.in/api/v2/validate",
            "variables": {}
        }
    ],
    "paths": {
        "/create": {
            "post": {
                "summary": "Create Order MicroService",
                "operationId": "CreateOrderMicroService",
                "parameters": [
                    {
                        "name": "cache-control",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "no-cache"
                        }
                    },
                    {
                        "name": "postman-token",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "58162b8a-54be-4f13-934d-07199ce8982d"
                        }
                    },
                    {
                        "name": "x-verify",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "B69107523187C4313FA2DB94568791C50F7BDA366052367A4622A870C327B06A"
                        }
                    },
                    {
                        "name": "Cookie",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "ASP.NET_SessionId=zjvzodvatuaxp2o0rnf2xapz"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "allOf": [
                                    {
                                        "$ref": "#/components/schemas/CreateOrderMicroServiceRequest"
                                    },
                                    {
                                        "example": {
                                            "request": "ewogICJtZXJjaGFudF9kYXRhIjogewogICAgIm1lcmNoYW50X2lkIjogIjUwIiwKICAgICJtZXJjaGFudF9hY2Nlc3NfY29kZSI6ICI4MjRmNWViYy0xMDhlLTQ2NjYtYjJiYy02ZDk4NjQ0ZGY5ZDgiLAogICAgIm1lcmNoYW50X3JldHVybl91cmwiOiAiaHR0cDovLzEwLjIwMC4xNDYuMTM5L2NoYXJnaW5ncmVzcG5ldy5hc3B4IiwKICAgICJtZXJjaGFudF9vcmRlcl9pZCI6ICJPcmRlclBsdXJhbE1pY3JvXzAwNSIKICB9LAogICJwYXltZW50X2luZm9fZGF0YSI6IHsKICAgICJhbW91bnQiOiAyMDAsCiAgICAiY3VycmVuY3lfY29kZSI6ICJJTlIiLAogICAgIm9yZGVyX2Rlc2MiOiAiVGVzdCBPcmRlciIKICB9LAogICJjdXN0b21lcl9kYXRhIjogewogICAgImNvdW50cnlfY29kZSI6ICI5MSIsCiAgICAibW9iaWxlX251bWJlciI6ICI5MDUwMTU3OTc4IiwKICAgICJlbWFpbF9pZCI6ICJiYWx3YW50LnNpbmdoQHBpbmVsYWJzLmNvbSIKICB9LAogICJiaWxsaW5nX2FkZHJlc3NfZGF0YSI6IHsKICAgICJmaXJzdF9uYW1lIjogIkFua2l0IiwKICAgICJsYXN0X25hbWUiOiAiQW5lamEiLAogICAgImFkZHJlc3MxIjogIkhpc2FyIiwKICAgICJhZGRyZXNzMiI6ICJIaXNhciIsCiAgICAiYWRkcmVzczMiOiAiSGlzYXIiLAogICAgInBpbl9jb2RlIjogIjEyNTAwNSIsCiAgICAiY2l0eSI6ICJIaXNhciIsCiAgICAic3RhdGUiOiAiSGFyeWFuYSIsCiAgICAiY291bnRyeSI6ICJJbmRpYSIKICB9LAogICJzaGlwcGluZ19hZGRyZXNzX2RhdGEiOiB7CiAgICAiZmlyc3RfbmFtZSI6ICJBbmtpdCIsCiAgICAibGFzdF9uYW1lIjogIkFuZWphIiwKICAgICJhZGRyZXNzMSI6ICJIaXNhciIsCiAgICAiYWRkcmVzczIiOiAiSGlzYXIiLAogICAgImFkZHJlc3MzIjogIkhpc2FyIiwKICAgICJwaW5fY29kZSI6ICIxMjUwMDUiLAogICAgImNpdHkiOiAiSGlzYXIiLAogICAgInN0YXRlIjogIkhhcnlhbmEiLAogICAgImNvdW50cnkiOiAiSW5kaWEiCiAgfSwKICAicHJvZHVjdF9pbmZvX2RhdGEiOiB7CiAgICAicHJvZHVjdF9kZXRhaWxzIjogWwogICAgICB7CiAgICAgICAgInByb2R1Y3RfY29kZSI6ICJ0ZXN0IiwKICAgICAgICAicHJvZHVjdF9hbW91bnQiOiAyMDAKICAgICAgfQogICAgXQogIH0sCiAgImFkZGl0aW9uYWxfaW5mb19kYXRhIjogewogICAgInJmdTEiOiAiMTIzIgogIH0KfQ=="
                                        }
                                    }
                                ]
                            },
                            "example": {
                                "request": "ewogICJtZXJjaGFudF9kYXRhIjogewogICAgIm1lcmNoYW50X2lkIjogIjUwIiwKICAgICJtZXJjaGFudF9hY2Nlc3NfY29kZSI6ICI4MjRmNWViYy0xMDhlLTQ2NjYtYjJiYy02ZDk4NjQ0ZGY5ZDgiLAogICAgIm1lcmNoYW50X3JldHVybl91cmwiOiAiaHR0cDovLzEwLjIwMC4xNDYuMTM5L2NoYXJnaW5ncmVzcG5ldy5hc3B4IiwKICAgICJtZXJjaGFudF9vcmRlcl9pZCI6ICJPcmRlclBsdXJhbE1pY3JvXzAwNSIKICB9LAogICJwYXltZW50X2luZm9fZGF0YSI6IHsKICAgICJhbW91bnQiOiAyMDAsCiAgICAiY3VycmVuY3lfY29kZSI6ICJJTlIiLAogICAgIm9yZGVyX2Rlc2MiOiAiVGVzdCBPcmRlciIKICB9LAogICJjdXN0b21lcl9kYXRhIjogewogICAgImNvdW50cnlfY29kZSI6ICI5MSIsCiAgICAibW9iaWxlX251bWJlciI6ICI5MDUwMTU3OTc4IiwKICAgICJlbWFpbF9pZCI6ICJiYWx3YW50LnNpbmdoQHBpbmVsYWJzLmNvbSIKICB9LAogICJiaWxsaW5nX2FkZHJlc3NfZGF0YSI6IHsKICAgICJmaXJzdF9uYW1lIjogIkFua2l0IiwKICAgICJsYXN0X25hbWUiOiAiQW5lamEiLAogICAgImFkZHJlc3MxIjogIkhpc2FyIiwKICAgICJhZGRyZXNzMiI6ICJIaXNhciIsCiAgICAiYWRkcmVzczMiOiAiSGlzYXIiLAogICAgInBpbl9jb2RlIjogIjEyNTAwNSIsCiAgICAiY2l0eSI6ICJIaXNhciIsCiAgICAic3RhdGUiOiAiSGFyeWFuYSIsCiAgICAiY291bnRyeSI6ICJJbmRpYSIKICB9LAogICJzaGlwcGluZ19hZGRyZXNzX2RhdGEiOiB7CiAgICAiZmlyc3RfbmFtZSI6ICJBbmtpdCIsCiAgICAibGFzdF9uYW1lIjogIkFuZWphIiwKICAgICJhZGRyZXNzMSI6ICJIaXNhciIsCiAgICAiYWRkcmVzczIiOiAiSGlzYXIiLAogICAgImFkZHJlc3MzIjogIkhpc2FyIiwKICAgICJwaW5fY29kZSI6ICIxMjUwMDUiLAogICAgImNpdHkiOiAiSGlzYXIiLAogICAgInN0YXRlIjogIkhhcnlhbmEiLAogICAgImNvdW50cnkiOiAiSW5kaWEiCiAgfSwKICAicHJvZHVjdF9pbmZvX2RhdGEiOiB7CiAgICAicHJvZHVjdF9kZXRhaWxzIjogWwogICAgICB7CiAgICAgICAgInByb2R1Y3RfY29kZSI6ICJ0ZXN0IiwKICAgICAgICAicHJvZHVjdF9hbW91bnQiOiAyMDAKICAgICAgfQogICAgXQogIH0sCiAgImFkZGl0aW9uYWxfaW5mb19kYXRhIjogewogICAgInJmdTEiOiAiMTIzIgogIH0KfQ=="
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false,
                "servers": [
                    {
                        "url": "https://api.pluralonline.com/api/v1/order",
                        "variables": {}
                    }
                ]
            }
        },
        "/v1/order/create": {
            "post": {
                "summary": "Create Order MicroService  Copy",
                "operationId": "CreateOrderMicroServiceCopy",
                "parameters": [
                    {
                        "name": "cache-control",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "no-cache"
                        }
                    },
                    {
                        "name": "postman-token",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "58162b8a-54be-4f13-934d-07199ce8982d"
                        }
                    },
                    {
                        "name": "x-verify",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "6DF09677143B6E33F6ED914577FD884E5643E308FC81029FE4B61BE90972743D"
                        }
                    },
                    {
                        "name": "Cookie",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "ASP.NET_SessionId=zjvzodvatuaxp2o0rnf2xapz"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "allOf": [
                                    {
                                        "$ref": "#/components/schemas/CreateOrderMicroServiceCopyRequest"
                                    },
                                    {
                                        "example": {
                                            "request": "ewogICJtZXJjaGFudF9kYXRhIjogewogICAgIm1lcmNoYW50X2lkIjogIjE3NyIsCiAgICAibWVyY2hhbnRfYWNjZXNzX2NvZGUiOiAiYmM1NDc2ZGUtNDkxZi00NzhlLTk3YmYtNjdjYTEwMWY3YTNhIiwKICAgICJtZXJjaGFudF9yZXR1cm5fdXJsIjogImh0dHA6Ly8xMC4yMDguOC4xMzk6OTAyMC9jaGFyZ2luZ3Jlc3BuZXcuYXNweCIsCiAgICAibWVyY2hhbnRfb3JkZXJfaWQiOiAiT3JkZXJQbHVyYWxNaWNyb18wMDE5IgogIH0sCiAgInBheW1lbnRfaW5mb19kYXRhIjogewogICAgImFtb3VudCI6IDIwMCwKICAgICJjdXJyZW5jeV9jb2RlIjogIklOUiIsCiAgICAib3JkZXJfZGVzYyI6ICJUZXN0IE9yZGVyIiwKInByZWZlcnJlZF9nYXRld2F5cyI6IlJBWk9SX1BBWSIKICB9LAogICJjdXN0b21lcl9kYXRhIjogewogICAgImNvdW50cnlfY29kZSI6ICI5MSIsCiAgICAibW9iaWxlX251bWJlciI6ICI5MDUwMTU3OTc4IiwKICAgICJlbWFpbF9pZCI6ICJiYWx3YW50LnNpbmdoQHBpbmVsYWJzLmNvbSIKICB9LAogICJiaWxsaW5nX2FkZHJlc3NfZGF0YSI6IHsKICAgICJmaXJzdF9uYW1lIjogIkFua2l0IiwKICAgICJsYXN0X25hbWUiOiAiQW5lamEiLAogICAgImFkZHJlc3MxIjogIkhpc2FyIiwKICAgICJhZGRyZXNzMiI6ICJIaXNhciIsCiAgICAiYWRkcmVzczMiOiAiSGlzYXIiLAogICAgInBpbl9jb2RlIjogIjEyNTAwNSIsCiAgICAiY2l0eSI6ICJIaXNhciIsCiAgICAic3RhdGUiOiAiSGFyeWFuYSIsCiAgICAiY291bnRyeSI6ICJJbmRpYSIKICB9LAogICJzaGlwcGluZ19hZGRyZXNzX2RhdGEiOiB7CiAgICAiZmlyc3RfbmFtZSI6ICJBbmtpdCIsCiAgICAibGFzdF9uYW1lIjogIkFuZWphIiwKICAgICJhZGRyZXNzMSI6ICJIaXNhciIsCiAgICAiYWRkcmVzczIiOiAiSGlzYXIiLAogICAgImFkZHJlc3MzIjogIkhpc2FyIiwKICAgICJwaW5fY29kZSI6ICIxMjUwMDUiLAogICAgImNpdHkiOiAiSGlzYXIiLAogICAgInN0YXRlIjogIkhhcnlhbmEiLAogICAgImNvdW50cnkiOiAiSW5kaWEiCiAgfSwKICAicHJvZHVjdF9pbmZvX2RhdGEiOiB7CiAgICAicHJvZHVjdF9kZXRhaWxzIjogWwogICAgICB7CiAgICAgICAgInByb2R1Y3RfY29kZSI6ICJ0ZXN0IiwKICAgICAgICAicHJvZHVjdF9hbW91bnQiOiAyMDAKICAgICAgfQogICAgXQogIH0sCiAgImFkZGl0aW9uYWxfaW5mb19kYXRhIjogewogICAgInJmdTEiOiAiMTIzIgogIH0KfQ=="
                                        }
                                    }
                                ]
                            },
                            "example": {
                                "request": "ewogICJtZXJjaGFudF9kYXRhIjogewogICAgIm1lcmNoYW50X2lkIjogIjE3NyIsCiAgICAibWVyY2hhbnRfYWNjZXNzX2NvZGUiOiAiYmM1NDc2ZGUtNDkxZi00NzhlLTk3YmYtNjdjYTEwMWY3YTNhIiwKICAgICJtZXJjaGFudF9yZXR1cm5fdXJsIjogImh0dHA6Ly8xMC4yMDguOC4xMzk6OTAyMC9jaGFyZ2luZ3Jlc3BuZXcuYXNweCIsCiAgICAibWVyY2hhbnRfb3JkZXJfaWQiOiAiT3JkZXJQbHVyYWxNaWNyb18wMDE5IgogIH0sCiAgInBheW1lbnRfaW5mb19kYXRhIjogewogICAgImFtb3VudCI6IDIwMCwKICAgICJjdXJyZW5jeV9jb2RlIjogIklOUiIsCiAgICAib3JkZXJfZGVzYyI6ICJUZXN0IE9yZGVyIiwKInByZWZlcnJlZF9nYXRld2F5cyI6IlJBWk9SX1BBWSIKICB9LAogICJjdXN0b21lcl9kYXRhIjogewogICAgImNvdW50cnlfY29kZSI6ICI5MSIsCiAgICAibW9iaWxlX251bWJlciI6ICI5MDUwMTU3OTc4IiwKICAgICJlbWFpbF9pZCI6ICJiYWx3YW50LnNpbmdoQHBpbmVsYWJzLmNvbSIKICB9LAogICJiaWxsaW5nX2FkZHJlc3NfZGF0YSI6IHsKICAgICJmaXJzdF9uYW1lIjogIkFua2l0IiwKICAgICJsYXN0X25hbWUiOiAiQW5lamEiLAogICAgImFkZHJlc3MxIjogIkhpc2FyIiwKICAgICJhZGRyZXNzMiI6ICJIaXNhciIsCiAgICAiYWRkcmVzczMiOiAiSGlzYXIiLAogICAgInBpbl9jb2RlIjogIjEyNTAwNSIsCiAgICAiY2l0eSI6ICJIaXNhciIsCiAgICAic3RhdGUiOiAiSGFyeWFuYSIsCiAgICAiY291bnRyeSI6ICJJbmRpYSIKICB9LAogICJzaGlwcGluZ19hZGRyZXNzX2RhdGEiOiB7CiAgICAiZmlyc3RfbmFtZSI6ICJBbmtpdCIsCiAgICAibGFzdF9uYW1lIjogIkFuZWphIiwKICAgICJhZGRyZXNzMSI6ICJIaXNhciIsCiAgICAiYWRkcmVzczIiOiAiSGlzYXIiLAogICAgImFkZHJlc3MzIjogIkhpc2FyIiwKICAgICJwaW5fY29kZSI6ICIxMjUwMDUiLAogICAgImNpdHkiOiAiSGlzYXIiLAogICAgInN0YXRlIjogIkhhcnlhbmEiLAogICAgImNvdW50cnkiOiAiSW5kaWEiCiAgfSwKICAicHJvZHVjdF9pbmZvX2RhdGEiOiB7CiAgICAicHJvZHVjdF9kZXRhaWxzIjogWwogICAgICB7CiAgICAgICAgInByb2R1Y3RfY29kZSI6ICJ0ZXN0IiwKICAgICAgICAicHJvZHVjdF9hbW91bnQiOiAyMDAKICAgICAgfQogICAgXQogIH0sCiAgImFkZGl0aW9uYWxfaW5mb19kYXRhIjogewogICAgInJmdTEiOiAiMTIzIgogIH0KfQ=="
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false,
                "servers": [
                    {
                        "url": "https://pluralqa.pinepg.in/api",
                        "variables": {}
                    }
                ]
            }
        },
        "/payment": {
            "post": {
                "summary": "Process Payment CCDC",
                "operationId": "ProcessPaymentCCDC",
                "parameters": [
                    {
                        "name": "token",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "ndCyCFJkVd3WQSByQJtFHNinE7yx6NQSedzapwtOVyk="
                        }
                    },
                    {
                        "name": "Cookie",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "ASP.NET_SessionId=zjvzodvatuaxp2o0rnf2xapz; ASP.NET_SessionId=zjvzodvatuaxp2o0rnf2xapz"
                        }
                    },
                    {
                        "name": "checkoutmode",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "SEAMLESS"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "allOf": [
                                    {
                                        "$ref": "#/components/schemas/ProcessPaymentCCDCRequest"
                                    },
                                    {
                                        "example": {
                                            "card_data": {
                                                "card_number": "4012001037141112",
                                                "cvv": "408",
                                                "card_holder_name": "BALWANT SINGH",
                                                "card_expiry_year": "2023",
                                                "card_expiry_month": "10",
                                                "is_card_to_be_saved": true
                                            },
                                            "customer_data": {
                                                "mobile_no": "9050157978",
                                                "country_code": "91",
                                                "email_id": "balwant.singh@pinelabs.com",
                                                "customer_token": "vQ7ssVqGlcfEUpGdzycwnQ=="
                                            }
                                        }
                                    }
                                ]
                            },
                            "example": {
                                "card_data": {
                                    "card_number": "4012001037141112",
                                    "cvv": "408",
                                    "card_holder_name": "BALWANT SINGH",
                                    "card_expiry_year": "2023",
                                    "card_expiry_month": "10",
                                    "is_card_to_be_saved": true
                                },
                                "customer_data": {
                                    "mobile_no": "9050157978",
                                    "country_code": "91",
                                    "email_id": "balwant.singh@pinelabs.com",
                                    "customer_token": "vQ7ssVqGlcfEUpGdzycwnQ=="
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false,
                "servers": [
                    {
                        "url": "https://api-staging.pluralonline.com/api/v1/card/process",
                        "variables": {}
                    }
                ]
            }
        },
        "/v1/netbanking/process/payment": {
            "post": {
                "summary": "NetBanking Process",
                "operationId": "NetBankingProcess",
                "parameters": [
                    {
                        "name": "token",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "hj5QygJU7+QZ19kvCZAlGHHv+EiRHDn8tz1Ish8pKqA="
                        }
                    },
                    {
                        "name": "checkoutmode",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "SEAMLESS"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "allOf": [
                                    {
                                        "$ref": "#/components/schemas/NetBankingProcessRequest"
                                    },
                                    {
                                        "example": {
                                            "netbanking_data": {
                                                "pay_code": "NB1531"
                                            },
                                            "customer_data": {
                                                "country_code": "91",
                                                "mobile_number": "9050157978",
                                                "email_id": "balwant.singh@pinelabs.com"
                                            }
                                        }
                                    }
                                ]
                            },
                            "example": {
                                "netbanking_data": {
                                    "pay_code": "NB1531"
                                },
                                "customer_data": {
                                    "country_code": "91",
                                    "mobile_number": "9050157978",
                                    "email_id": "balwant.singh@pinelabs.com"
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false,
                "servers": [
                    {
                        "url": "https://pluralqa.pinepg.in/api",
                        "variables": {}
                    }
                ]
            }
        },
        "/v1/upi/process/payment": {
            "post": {
                "summary": "UPI Process Payment",
                "operationId": "UPIProcessPayment",
                "parameters": [
                    {
                        "name": "token",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "av+yGbkpSPO58q3tksyjf3rZKZ1b5FqjvbQQJuRI3dk="
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "allOf": [
                                    {
                                        "$ref": "#/components/schemas/UPIProcessPaymentRequest"
                                    },
                                    {
                                        "example": {
                                            "upi_data": {
                                                "upi_option": "UPI",
                                                "vpa": "balwant.singh@hdfcbank"
                                            },
                                            "customer_data": {
                                                "mobile_no": "9050157978",
                                                "country_code": "91",
                                                "email_id": "balwant.singh@pinelabs.com",
                                                "customer_token": "vQ7ssVqGlcfEUpGdzycwnQ=="
                                            }
                                        }
                                    }
                                ]
                            },
                            "example": {
                                "upi_data": {
                                    "upi_option": "UPI",
                                    "vpa": "balwant.singh@hdfcbank"
                                },
                                "customer_data": {
                                    "mobile_no": "9050157978",
                                    "country_code": "91",
                                    "email_id": "balwant.singh@pinelabs.com",
                                    "customer_token": "vQ7ssVqGlcfEUpGdzycwnQ=="
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false,
                "servers": [
                    {
                        "url": "https://pluralqa.pinepg.in/api",
                        "variables": {}
                    }
                ]
            }
        },
        "/v1/wallet/process/payment": {
            "post": {
                "summary": "Process Payment Wallet",
                "operationId": "ProcessPaymentWallet",
                "parameters": [
                    {
                        "name": "token",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "hj5QygJU7+QZ19kvCZAlGHHv+EiRHDn8tz1Ish8pKqA="
                        }
                    },
                    {
                        "name": "Cookie",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "ASP.NET_SessionId=zjvzodvatuaxp2o0rnf2xapz"
                        }
                    },
                    {
                        "name": "checkoutmode",
                        "in": "header",
                        "description": "",
                        "required": true,
                        "style": "simple",
                        "schema": {
                            "type": "string",
                            "example": "SEAMLESS"
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "allOf": [
                                    {
                                        "$ref": "#/components/schemas/ProcessPaymentWalletRequest"
                                    },
                                    {
                                        "example": {
                                            "wallet_data": {
                                                "wallet_code": "payzapp",
                                                "mobile_number": "9050157978"
                                            },
                                            "customer_data": {
                                                "mobile_no": "9050157978",
                                                "country_code": "91",
                                                "email_id": "balwant.singh@pinelabs.com",
                                                "customer_token": "vQ7ssVqGlcfEUpGdzycwnQ=="
                                            }
                                        }
                                    }
                                ]
                            },
                            "example": {
                                "wallet_data": {
                                    "wallet_code": "payzapp",
                                    "mobile_number": "9050157978"
                                },
                                "customer_data": {
                                    "mobile_no": "9050157978",
                                    "country_code": "91",
                                    "email_id": "balwant.singh@pinelabs.com",
                                    "customer_token": "vQ7ssVqGlcfEUpGdzycwnQ=="
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false,
                "servers": [
                    {
                        "url": "https://pluralqa.pinepg.in/api",
                        "variables": {}
                    }
                ]
            }
        },
        "/card/v1/healthCheck": {
            "get": {
                "summary": "Card Health Check",
                "operationId": "CardHealthCheck",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false,
                "servers": [
                    {
                        "url": "https://pluralqa.pinepg.in/api",
                        "variables": {}
                    }
                ]
            }
        },
        "/v1/dashboard/auth/merchant/user/forgetpassword/fetch/otp": {
            "post": {
                "summary": "Fetch OTP",
                "operationId": "FetchOTP",
                "parameters": [],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "allOf": [
                                    {
                                        "$ref": "#/components/schemas/FetchOTPRequest"
                                    },
                                    {
                                        "example": {
                                            "otpToken": "06VRNs9vvHrWN5WXkf69gen0Ikzmb9yKk5oBSqeD4l2WNXEpBnyV%2B9LQMW8z%2FLB%2F"
                                        }
                                    }
                                ]
                            },
                            "example": {
                                "otpToken": "06VRNs9vvHrWN5WXkf69gen0Ikzmb9yKk5oBSqeD4l2WNXEpBnyV%2B9LQMW8z%2FLB%2F"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false,
                "servers": [
                    {
                        "url": "https://pluralqa.pinepg.in/api",
                        "variables": {}
                    }
                ]
            }
        },
        "/otp": {
            "post": {
                "summary": "Validate OTP",
                "operationId": "ValidateOTP",
                "parameters": [
                    {
                        "name": "token",
                        "in": "query",
                        "description": "",
                        "required": true,
                        "style": "form",
                        "explode": true,
                        "schema": {
                            "type": "string",
                            "example": "pKIL0tSO8g3fVI1UDpVKAOXHMxbDtQ7EmBYfo4E2TMM="
                        }
                    }
                ],
                "requestBody": {
                    "description": "",
                    "content": {
                        "application/json": {
                            "schema": {
                                "allOf": [
                                    {
                                        "$ref": "#/components/schemas/ValidateOTPRequest"
                                    },
                                    {
                                        "example": {
                                            "otp": "123456"
                                        }
                                    }
                                ]
                            },
                            "example": {
                                "otp": "123456"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "",
                        "headers": {}
                    }
                },
                "deprecated": false,
                "servers": [
                    {
                        "url": "https://test.pinepg.in/api/v2/validate",
                        "variables": {}
                    }
                ]
            }
        }
    },
    "components": {
        "schemas": {
            "CreateOrderMicroServiceRequest": {
                "title": "CreateOrderMicroServiceRequest",
                "required": ["request"],
                "type": "object",
                "properties": {
                    "request": {
                        "type": "string"
                    }
                },
                "example": {
                    "request": "ewogICJtZXJjaGFudF9kYXRhIjogewogICAgIm1lcmNoYW50X2lkIjogIjUwIiwKICAgICJtZXJjaGFudF9hY2Nlc3NfY29kZSI6ICI4MjRmNWViYy0xMDhlLTQ2NjYtYjJiYy02ZDk4NjQ0ZGY5ZDgiLAogICAgIm1lcmNoYW50X3JldHVybl91cmwiOiAiaHR0cDovLzEwLjIwMC4xNDYuMTM5L2NoYXJnaW5ncmVzcG5ldy5hc3B4IiwKICAgICJtZXJjaGFudF9vcmRlcl9pZCI6ICJPcmRlclBsdXJhbE1pY3JvXzAwNSIKICB9LAogICJwYXltZW50X2luZm9fZGF0YSI6IHsKICAgICJhbW91bnQiOiAyMDAsCiAgICAiY3VycmVuY3lfY29kZSI6ICJJTlIiLAogICAgIm9yZGVyX2Rlc2MiOiAiVGVzdCBPcmRlciIKICB9LAogICJjdXN0b21lcl9kYXRhIjogewogICAgImNvdW50cnlfY29kZSI6ICI5MSIsCiAgICAibW9iaWxlX251bWJlciI6ICI5MDUwMTU3OTc4IiwKICAgICJlbWFpbF9pZCI6ICJiYWx3YW50LnNpbmdoQHBpbmVsYWJzLmNvbSIKICB9LAogICJiaWxsaW5nX2FkZHJlc3NfZGF0YSI6IHsKICAgICJmaXJzdF9uYW1lIjogIkFua2l0IiwKICAgICJsYXN0X25hbWUiOiAiQW5lamEiLAogICAgImFkZHJlc3MxIjogIkhpc2FyIiwKICAgICJhZGRyZXNzMiI6ICJIaXNhciIsCiAgICAiYWRkcmVzczMiOiAiSGlzYXIiLAogICAgInBpbl9jb2RlIjogIjEyNTAwNSIsCiAgICAiY2l0eSI6ICJIaXNhciIsCiAgICAic3RhdGUiOiAiSGFyeWFuYSIsCiAgICAiY291bnRyeSI6ICJJbmRpYSIKICB9LAogICJzaGlwcGluZ19hZGRyZXNzX2RhdGEiOiB7CiAgICAiZmlyc3RfbmFtZSI6ICJBbmtpdCIsCiAgICAibGFzdF9uYW1lIjogIkFuZWphIiwKICAgICJhZGRyZXNzMSI6ICJIaXNhciIsCiAgICAiYWRkcmVzczIiOiAiSGlzYXIiLAogICAgImFkZHJlc3MzIjogIkhpc2FyIiwKICAgICJwaW5fY29kZSI6ICIxMjUwMDUiLAogICAgImNpdHkiOiAiSGlzYXIiLAogICAgInN0YXRlIjogIkhhcnlhbmEiLAogICAgImNvdW50cnkiOiAiSW5kaWEiCiAgfSwKICAicHJvZHVjdF9pbmZvX2RhdGEiOiB7CiAgICAicHJvZHVjdF9kZXRhaWxzIjogWwogICAgICB7CiAgICAgICAgInByb2R1Y3RfY29kZSI6ICJ0ZXN0IiwKICAgICAgICAicHJvZHVjdF9hbW91bnQiOiAyMDAKICAgICAgfQogICAgXQogIH0sCiAgImFkZGl0aW9uYWxfaW5mb19kYXRhIjogewogICAgInJmdTEiOiAiMTIzIgogIH0KfQ=="
                }
            },
            "CreateOrderMicroServiceCopyRequest": {
                "title": "CreateOrderMicroServiceCopyRequest",
                "required": ["request"],
                "type": "object",
                "properties": {
                    "request": {
                        "type": "string"
                    }
                },
                "example": {
                    "request": "ewogICJtZXJjaGFudF9kYXRhIjogewogICAgIm1lcmNoYW50X2lkIjogIjE3NyIsCiAgICAibWVyY2hhbnRfYWNjZXNzX2NvZGUiOiAiYmM1NDc2ZGUtNDkxZi00NzhlLTk3YmYtNjdjYTEwMWY3YTNhIiwKICAgICJtZXJjaGFudF9yZXR1cm5fdXJsIjogImh0dHA6Ly8xMC4yMDguOC4xMzk6OTAyMC9jaGFyZ2luZ3Jlc3BuZXcuYXNweCIsCiAgICAibWVyY2hhbnRfb3JkZXJfaWQiOiAiT3JkZXJQbHVyYWxNaWNyb18wMDE5IgogIH0sCiAgInBheW1lbnRfaW5mb19kYXRhIjogewogICAgImFtb3VudCI6IDIwMCwKICAgICJjdXJyZW5jeV9jb2RlIjogIklOUiIsCiAgICAib3JkZXJfZGVzYyI6ICJUZXN0IE9yZGVyIiwKInByZWZlcnJlZF9nYXRld2F5cyI6IlJBWk9SX1BBWSIKICB9LAogICJjdXN0b21lcl9kYXRhIjogewogICAgImNvdW50cnlfY29kZSI6ICI5MSIsCiAgICAibW9iaWxlX251bWJlciI6ICI5MDUwMTU3OTc4IiwKICAgICJlbWFpbF9pZCI6ICJiYWx3YW50LnNpbmdoQHBpbmVsYWJzLmNvbSIKICB9LAogICJiaWxsaW5nX2FkZHJlc3NfZGF0YSI6IHsKICAgICJmaXJzdF9uYW1lIjogIkFua2l0IiwKICAgICJsYXN0X25hbWUiOiAiQW5lamEiLAogICAgImFkZHJlc3MxIjogIkhpc2FyIiwKICAgICJhZGRyZXNzMiI6ICJIaXNhciIsCiAgICAiYWRkcmVzczMiOiAiSGlzYXIiLAogICAgInBpbl9jb2RlIjogIjEyNTAwNSIsCiAgICAiY2l0eSI6ICJIaXNhciIsCiAgICAic3RhdGUiOiAiSGFyeWFuYSIsCiAgICAiY291bnRyeSI6ICJJbmRpYSIKICB9LAogICJzaGlwcGluZ19hZGRyZXNzX2RhdGEiOiB7CiAgICAiZmlyc3RfbmFtZSI6ICJBbmtpdCIsCiAgICAibGFzdF9uYW1lIjogIkFuZWphIiwKICAgICJhZGRyZXNzMSI6ICJIaXNhciIsCiAgICAiYWRkcmVzczIiOiAiSGlzYXIiLAogICAgImFkZHJlc3MzIjogIkhpc2FyIiwKICAgICJwaW5fY29kZSI6ICIxMjUwMDUiLAogICAgImNpdHkiOiAiSGlzYXIiLAogICAgInN0YXRlIjogIkhhcnlhbmEiLAogICAgImNvdW50cnkiOiAiSW5kaWEiCiAgfSwKICAicHJvZHVjdF9pbmZvX2RhdGEiOiB7CiAgICAicHJvZHVjdF9kZXRhaWxzIjogWwogICAgICB7CiAgICAgICAgInByb2R1Y3RfY29kZSI6ICJ0ZXN0IiwKICAgICAgICAicHJvZHVjdF9hbW91bnQiOiAyMDAKICAgICAgfQogICAgXQogIH0sCiAgImFkZGl0aW9uYWxfaW5mb19kYXRhIjogewogICAgInJmdTEiOiAiMTIzIgogIH0KfQ=="
                }
            },
            "ProcessPaymentCCDCRequest": {
                "title": "ProcessPaymentCCDCRequest",
                "required": ["card_data", "customer_data"],
                "type": "object",
                "properties": {
                    "card_data": {
                        "$ref": "#/components/schemas/CardData"
                    },
                    "customer_data": {
                        "$ref": "#/components/schemas/CustomerData"
                    }
                },
                "example": {
                    "card_data": {
                        "card_number": "4012001037141112",
                        "cvv": "408",
                        "card_holder_name": "BALWANT SINGH",
                        "card_expiry_year": "2023",
                        "card_expiry_month": "10",
                        "is_card_to_be_saved": true
                    },
                    "customer_data": {
                        "mobile_no": "9050157978",
                        "country_code": "91",
                        "email_id": "balwant.singh@pinelabs.com",
                        "customer_token": "vQ7ssVqGlcfEUpGdzycwnQ=="
                    }
                }
            },
            "CardData": {
                "title": "CardData",
                "required": [
                    "card_number",
                    "cvv",
                    "card_holder_name",
                    "card_expiry_year",
                    "card_expiry_month",
                    "is_card_to_be_saved"
                ],
                "type": "object",
                "properties": {
                    "card_number": {
                        "type": "string"
                    },
                    "cvv": {
                        "type": "string"
                    },
                    "card_holder_name": {
                        "type": "string"
                    },
                    "card_expiry_year": {
                        "type": "string"
                    },
                    "card_expiry_month": {
                        "type": "string"
                    },
                    "is_card_to_be_saved": {
                        "type": "boolean"
                    }
                },
                "example": {
                    "card_number": "4012001037141112",
                    "cvv": "408",
                    "card_holder_name": "BALWANT SINGH",
                    "card_expiry_year": "2023",
                    "card_expiry_month": "10",
                    "is_card_to_be_saved": true
                }
            },
            "CustomerData": {
                "title": "CustomerData",
                "required": [
                    "mobile_no",
                    "country_code",
                    "email_id",
                    "customer_token"
                ],
                "type": "object",
                "properties": {
                    "mobile_no": {
                        "type": "string"
                    },
                    "country_code": {
                        "type": "string"
                    },
                    "email_id": {
                        "type": "string"
                    },
                    "customer_token": {
                        "type": "string"
                    }
                },
                "example": {
                    "mobile_no": "9050157978",
                    "country_code": "91",
                    "email_id": "balwant.singh@pinelabs.com",
                    "customer_token": "vQ7ssVqGlcfEUpGdzycwnQ=="
                }
            },
            "NetBankingProcessRequest": {
                "title": "NetBankingProcessRequest",
                "required": ["netbanking_data", "customer_data"],
                "type": "object",
                "properties": {
                    "netbanking_data": {
                        "$ref": "#/components/schemas/NetbankingData"
                    },
                    "customer_data": {
                        "$ref": "#/components/schemas/CustomerData1"
                    }
                },
                "example": {
                    "netbanking_data": {
                        "pay_code": "NB1531"
                    },
                    "customer_data": {
                        "country_code": "91",
                        "mobile_number": "9050157978",
                        "email_id": "balwant.singh@pinelabs.com"
                    }
                }
            },
            "NetbankingData": {
                "title": "NetbankingData",
                "required": ["pay_code"],
                "type": "object",
                "properties": {
                    "pay_code": {
                        "type": "string"
                    }
                },
                "example": {
                    "pay_code": "NB1531"
                }
            },
            "CustomerData1": {
                "title": "CustomerData1",
                "required": ["country_code", "mobile_number", "email_id"],
                "type": "object",
                "properties": {
                    "country_code": {
                        "type": "string"
                    },
                    "mobile_number": {
                        "type": "string"
                    },
                    "email_id": {
                        "type": "string"
                    }
                },
                "example": {
                    "country_code": "91",
                    "mobile_number": "9050157978",
                    "email_id": "balwant.singh@pinelabs.com"
                }
            },
            "UPIProcessPaymentRequest": {
                "title": "UPIProcessPaymentRequest",
                "required": ["upi_data", "customer_data"],
                "type": "object",
                "properties": {
                    "upi_data": {
                        "$ref": "#/components/schemas/UpiData"
                    },
                    "customer_data": {
                        "$ref": "#/components/schemas/CustomerData"
                    }
                },
                "example": {
                    "upi_data": {
                        "upi_option": "UPI",
                        "vpa": "balwant.singh@hdfcbank"
                    },
                    "customer_data": {
                        "mobile_no": "9050157978",
                        "country_code": "91",
                        "email_id": "balwant.singh@pinelabs.com",
                        "customer_token": "vQ7ssVqGlcfEUpGdzycwnQ=="
                    }
                }
            },
            "UpiData": {
                "title": "UpiData",
                "required": ["upi_option", "vpa"],
                "type": "object",
                "properties": {
                    "upi_option": {
                        "type": "string"
                    },
                    "vpa": {
                        "type": "string"
                    }
                },
                "example": {
                    "upi_option": "UPI",
                    "vpa": "balwant.singh@hdfcbank"
                }
            },
            "ProcessPaymentWalletRequest": {
                "title": "ProcessPaymentWalletRequest",
                "required": ["wallet_data", "customer_data"],
                "type": "object",
                "properties": {
                    "wallet_data": {
                        "$ref": "#/components/schemas/WalletData"
                    },
                    "customer_data": {
                        "$ref": "#/components/schemas/CustomerData"
                    }
                },
                "example": {
                    "wallet_data": {
                        "wallet_code": "payzapp",
                        "mobile_number": "9050157978"
                    },
                    "customer_data": {
                        "mobile_no": "9050157978",
                        "country_code": "91",
                        "email_id": "balwant.singh@pinelabs.com",
                        "customer_token": "vQ7ssVqGlcfEUpGdzycwnQ=="
                    }
                }
            },
            "WalletData": {
                "title": "WalletData",
                "required": ["wallet_code", "mobile_number"],
                "type": "object",
                "properties": {
                    "wallet_code": {
                        "type": "string"
                    },
                    "mobile_number": {
                        "type": "string"
                    }
                },
                "example": {
                    "wallet_code": "payzapp",
                    "mobile_number": "9050157978"
                }
            },
            "FetchOTPRequest": {
                "title": "FetchOTPRequest",
                "required": ["otpToken"],
                "type": "object",
                "properties": {
                    "otpToken": {
                        "type": "string"
                    }
                },
                "example": {
                    "otpToken": "06VRNs9vvHrWN5WXkf69gen0Ikzmb9yKk5oBSqeD4l2WNXEpBnyV%2B9LQMW8z%2FLB%2F"
                }
            },
            "ValidateOTPRequest": {
                "title": "ValidateOTPRequest",
                "required": ["otp"],
                "type": "object",
                "properties": {
                    "otp": {
                        "type": "string"
                    }
                },
                "example": {
                    "otp": "123456"
                }
            }
        }
    },
    "tags": [
        {
            "name": "Misc",
            "description": ""
        }
    ]
}
