{
  "openapi": "3.0.0",
  "info": {
    "title": "FIU service",
    "description": "Build financial services using Setu's Account Aggregator",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://fiu-uat.setu.co",
      "variables": {}
    }
  ],
  "paths": {
    "/consents": {
      "post": {
        "tags": [
          "Consent APIs"
        ],
        "summary": "Create new consent",
        "description": "Call this API to create a consent request. Update Customer.id with your mobile number to be able to test the flow. This API responds with a **url** to initiate consent review flow as part of the response, with consent status as PENDING.  \nRead more about consent review by customer <a href='https://docs.setu.co/data/account-aggregator/api-integration/consent-flow#consent-review-by-customer' target='_blank'>here</a>",
        "operationId": "Createnewconsent",
        "parameters": [
          {
            "name": "x-client-id",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "test-client"
            }
          },
          {
            "name": "x-client-secret",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "3fa14d45-3adc-4522-b512-1e3f24d92568"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/CreatenewconsentRequest"
                  }
                ]
              },
              "example": {
                "Detail": {
                  "consentStart": "{{$isoTimestamp}}",
                  "consentExpiry": "2023-04-23T05:44:53.822Z",
                  "Customer": {
                    "id": "9999999999@onemoney"
                  },
                  "FIDataRange": {
                    "from": "2021-04-01T00:00:00Z",
                    "to": "2021-10-01T00:00:00Z"
                  },
                  "consentMode": "STORE",
                  "consentTypes": [
                    "TRANSACTIONS",
                    "PROFILE",
                    "SUMMARY"
                  ],
                  "fetchType": "PERIODIC",
                  "Frequency": {
                    "value": 30,
                    "unit": "MONTH"
                  },
                  "DataFilter": [
                    {
                      "type": "TRANSACTIONAMOUNT",
                      "value": "5000",
                      "operator": ">="
                    }
                  ],
                  "DataLife": {
                    "value": 1,
                    "unit": "MONTH"
                  },
                  "DataConsumer": {
                    "id": "setu-fiu-id"
                  },
                  "Purpose": {
                    "Category": {
                      "type": "string"
                    },
                    "code": "101",
                    "text": "Loan underwriting",
                    "refUri": "https://api.rebit.org.in/aa/purpose/101.xml"
                  },
                  "fiTypes": [
                    "DEPOSIT"
                  ]
                },
                "context": [
                  {
                    "key": "accounttype",
                    "value": "CURRENT"
                  }
                ],
                "redirectUrl": "https://setu.co"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/consents/{id}": {
      "get": {
        "tags": [
          "Consent APIs"
        ],
        "summary": "Get a consent",
        "description": "Call this API to get the updated status of a consent request by passing its unique `id`. If the consent is approved, the Status in the response will be `ACTIVE`. After this, you can now initiate Data flow for the approved consent request.",
        "operationId": "Getaconsent",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "x-client-id",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "test-client"
            }
          },
          {
            "name": "x-client-secret",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "3fa14d45-3adc-4522-b512-1e3f24d92568"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/sessions": {
      "post": {
        "tags": [
          "Data session APIs"
        ],
        "summary": "Create new data session",
        "description": "Call this API to create a data session against the approved `consentId`. Specify the format in which you wish to receive the decrypted financial data, this can be **xml** or **json.** Make sure that values of `DataRange` array in the body, matches or is within the `FIDataRange` specified in the Create consent request API.",
        "operationId": "Createnewdatasession",
        "parameters": [
          {
            "name": "x-client-id",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "test-client"
            }
          },
          {
            "name": "x-client-secret",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "3fa14d45-3adc-4522-b512-1e3f24d92568"
            }
          }
        ],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "allOf": [
                  {
                    "$ref": "#/components/schemas/CreatenewdatasessionRequest"
                  }
                ]
              },
              "example": {
                "consentId": "",
                "DataRange": {
                  "from": "2021-04-01T00:00:00Z",
                  "to": "2021-09-30T00:00:00Z"
                },
                "format": "json"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/sessions/{id}": {
      "get": {
        "tags": [
          "Data session APIs"
        ],
        "summary": "Get data",
        "description": "The notification URL you have configured with Setu will be used to notify you when data is ready to be fetched. Then, use the `id` received in Create Data Session API in the previous step to call this API to fetch the financial information of your user.",
        "operationId": "Getdata",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "x-client-id",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "test-client"
            }
          },
          {
            "name": "x-client-secret",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "3fa14d45-3adc-4522-b512-1e3f24d92568"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/fips": {
      "get": {
        "tags": [
          "FIU Data"
        ],
        "summary": "Get FIPs List",
        "operationId": "GetFIPsList",
        "parameters": [
          {
            "name": "x-client-id",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "test-client"
            }
          },
          {
            "name": "x-client-secret",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "3fa14d45-3adc-4522-b512-1e3f24d92568"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "CreatenewconsentRequest": {
        "title": "CreatenewconsentRequest",
        "required": [
          "Detail",
          "context",
          "redirectUrl"
        ],
        "type": "object",
        "properties": {
          "Detail": {
            "$ref": "#/components/schemas/Detail"
          },
          "context": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Context"
            },
            "description": ""
          },
          "redirectUrl": {
            "type": "string"
          }
        },
        "example": {
          "Detail": {
            "consentStart": "{{$isoTimestamp}}",
            "consentExpiry": "2023-04-23T05:44:53.822Z",
            "Customer": {
              "id": "9999999999@onemoney"
            },
            "FIDataRange": {
              "from": "2021-04-01T00:00:00Z",
              "to": "2021-10-01T00:00:00Z"
            },
            "consentMode": "STORE",
            "consentTypes": [
              "TRANSACTIONS",
              "PROFILE",
              "SUMMARY"
            ],
            "fetchType": "PERIODIC",
            "Frequency": {
              "value": 30,
              "unit": "MONTH"
            },
            "DataFilter": [
              {
                "type": "TRANSACTIONAMOUNT",
                "value": "5000",
                "operator": ">="
              }
            ],
            "DataLife": {
              "value": 1,
              "unit": "MONTH"
            },
            "DataConsumer": {
              "id": "setu-fiu-id"
            },
            "Purpose": {
              "Category": {
                "type": "string"
              },
              "code": "101",
              "text": "Loan underwriting",
              "refUri": "https://api.rebit.org.in/aa/purpose/101.xml"
            },
            "fiTypes": [
              "DEPOSIT"
            ]
          },
          "context": [
            {
              "key": "accounttype",
              "value": "CURRENT"
            }
          ],
          "redirectUrl": "https://setu.co"
        }
      },
      "Detail": {
        "title": "Detail",
        "required": [
          "consentStart",
          "consentExpiry",
          "Customer",
          "FIDataRange",
          "consentMode",
          "consentTypes",
          "fetchType",
          "Frequency",
          "DataFilter",
          "DataLife",
          "DataConsumer",
          "Purpose",
          "fiTypes"
        ],
        "type": "object",
        "properties": {
          "consentStart": {
            "type": "string"
          },
          "consentExpiry": {
            "type": "string"
          },
          "Customer": {
            "$ref": "#/components/schemas/Customer"
          },
          "FIDataRange": {
            "$ref": "#/components/schemas/FIDataRange"
          },
          "consentMode": {
            "type": "string"
          },
          "consentTypes": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          },
          "fetchType": {
            "type": "string"
          },
          "Frequency": {
            "$ref": "#/components/schemas/Frequency"
          },
          "DataFilter": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/DataFilter"
            },
            "description": ""
          },
          "DataLife": {
            "$ref": "#/components/schemas/DataLife"
          },
          "DataConsumer": {
            "$ref": "#/components/schemas/DataConsumer"
          },
          "Purpose": {
            "$ref": "#/components/schemas/Purpose"
          },
          "fiTypes": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": ""
          }
        },
        "example": {
          "consentStart": "{{$isoTimestamp}}",
          "consentExpiry": "2023-04-23T05:44:53.822Z",
          "Customer": {
            "id": "9999999999@onemoney"
          },
          "FIDataRange": {
            "from": "2021-04-01T00:00:00Z",
            "to": "2021-10-01T00:00:00Z"
          },
          "consentMode": "STORE",
          "consentTypes": [
            "TRANSACTIONS",
            "PROFILE",
            "SUMMARY"
          ],
          "fetchType": "PERIODIC",
          "Frequency": {
            "value": 30,
            "unit": "MONTH"
          },
          "DataFilter": [
            {
              "type": "TRANSACTIONAMOUNT",
              "value": "5000",
              "operator": ">="
            }
          ],
          "DataLife": {
            "value": 1,
            "unit": "MONTH"
          },
          "DataConsumer": {
            "id": "setu-fiu-id"
          },
          "Purpose": {
            "Category": {
              "type": "string"
            },
            "code": "101",
            "text": "Loan underwriting",
            "refUri": "https://api.rebit.org.in/aa/purpose/101.xml"
          },
          "fiTypes": [
            "DEPOSIT"
          ]
        }
      },
      "Customer": {
        "title": "Customer",
        "required": [
          "id"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          }
        },
        "example": {
          "id": "9999999999@onemoney"
        }
      },
      "FIDataRange": {
        "title": "FIDataRange",
        "required": [
          "from",
          "to"
        ],
        "type": "object",
        "properties": {
          "from": {
            "type": "string"
          },
          "to": {
            "type": "string"
          }
        },
        "example": {
          "from": "2021-04-01T00:00:00Z",
          "to": "2021-10-01T00:00:00Z"
        }
      },
      "Frequency": {
        "title": "Frequency",
        "required": [
          "value",
          "unit"
        ],
        "type": "object",
        "properties": {
          "value": {
            "type": "integer",
            "format": "int32"
          },
          "unit": {
            "type": "string"
          }
        },
        "example": {
          "value": 30,
          "unit": "MONTH"
        }
      },
      "DataFilter": {
        "title": "DataFilter",
        "required": [
          "type",
          "value",
          "operator"
        ],
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          },
          "value": {
            "type": "string"
          },
          "operator": {
            "type": "string"
          }
        },
        "example": {
          "type": "TRANSACTIONAMOUNT",
          "value": "5000",
          "operator": ">="
        }
      },
      "DataLife": {
        "title": "DataLife",
        "required": [
          "value",
          "unit"
        ],
        "type": "object",
        "properties": {
          "value": {
            "type": "integer",
            "format": "int32"
          },
          "unit": {
            "type": "string"
          }
        },
        "example": {
          "value": 1,
          "unit": "MONTH"
        }
      },
      "DataConsumer": {
        "title": "DataConsumer",
        "required": [
          "id"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          }
        },
        "example": {
          "id": "setu-fiu-id"
        }
      },
      "Purpose": {
        "title": "Purpose",
        "required": [
          "Category",
          "code",
          "text",
          "refUri"
        ],
        "type": "object",
        "properties": {
          "Category": {
            "$ref": "#/components/schemas/Category"
          },
          "code": {
            "type": "string"
          },
          "text": {
            "type": "string"
          },
          "refUri": {
            "type": "string"
          }
        },
        "example": {
          "Category": {
            "type": "string"
          },
          "code": "101",
          "text": "Loan underwriting",
          "refUri": "https://api.rebit.org.in/aa/purpose/101.xml"
        }
      },
      "Category": {
        "title": "Category",
        "required": [
          "type"
        ],
        "type": "object",
        "properties": {
          "type": {
            "type": "string"
          }
        },
        "example": {
          "type": "string"
        }
      },
      "Context": {
        "title": "Context",
        "required": [
          "key",
          "value"
        ],
        "type": "object",
        "properties": {
          "key": {
            "type": "string"
          },
          "value": {
            "type": "string"
          }
        },
        "example": {
          "key": "accounttype",
          "value": "CURRENT"
        }
      },
      "CreatenewdatasessionRequest": {
        "title": "CreatenewdatasessionRequest",
        "required": [
          "consentId",
          "DataRange",
          "format"
        ],
        "type": "object",
        "properties": {
          "consentId": {
            "type": "string"
          },
          "DataRange": {
            "$ref": "#/components/schemas/DataRange"
          },
          "format": {
            "type": "string"
          }
        },
        "example": {
          "consentId": "",
          "DataRange": {
            "from": "2021-04-01T00:00:00Z",
            "to": "2021-09-30T00:00:00Z"
          },
          "format": "json"
        }
      },
      "DataRange": {
        "title": "DataRange",
        "required": [
          "from",
          "to"
        ],
        "type": "object",
        "properties": {
          "from": {
            "type": "string"
          },
          "to": {
            "type": "string"
          }
        },
        "example": {
          "from": "2021-04-01T00:00:00Z",
          "to": "2021-09-30T00:00:00Z"
        }
      }
    }
  },
  "tags": [
    {
      "name": "Consent APIs"
    },
    {
      "name": "Data session APIs"
    },
    {
      "name": "FIU Data"
    }
  ]
}
