{
  "openapi": "3.0.0",
  "info": {
    "title": "Data Gateway - eKYC",
    "description": "It allows you to create an eKYC request, which generates a verification URL. Once the aadhaar holder completes the Aadhaar verification process, the eKYC data can be retrieved.",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://dg-sandbox.setu.co",
      "description": "Sandbox"
    },
    {
      "url": "https://dg.setu.co",
      "description": "Production"
    }
  ],
  "paths": {
    "/v1/ekyc": {
      "post": {
        "summary": "Create eKYC Request",
        "operationId": "CreateaneKYCRequest",
        "parameters": [
          {
            "name": "x-client-id",
            "in": "header",
            "description": "Client id of the customer",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{client_id}}"
            }
          },
          {
            "name": "x-client-secret",
            "in": "header",
            "description": "Client secret of the customer",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{secret}}"
            }
          },
          {
            "name": "x-product-instance-id",
            "in": "header",
            "description": "Setu-ekyc product instance id",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{x-product-instance-id}}"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "CREATED",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/success"
                    },
                    {
                      "example": {
                        "id": "0c624d3e-9cb0-4323-b468-d89092d7d305",
                        "status": "CREATED",
                        "kycUrl": "http://localhost:3100/ekyc-web/0c624d3e-9cb0-4323-b468-d89092d7d305"
                      }
                    }
                  ]
                },
                "example": {
                  "id": "0c624d3e-9cb0-4323-b468-d89092d7d305",
                  "status": "CREATED",
                  "kycUrl": "http://localhost:3100/ekyc-web/0c624d3e-9cb0-4323-b468-d89092d7d305"
                }
              }
            }
          },
          "400": {
            "description": "BAD REQUEST",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/failure"
                    },
                    {
                      "example": {
                        "errorCode": "invalid_request",
                        "errorMsg": "validation error: Field required"
                      }
                    }
                  ]
                },
                "example": {
                  "errorCode": "invalid_request",
                  "errorMsg": "validation error: Field required"
                }
              }
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/failure"
                    },
                    {
                      "example": {
                        "errorCode": "internal_server_error",
                        "errorMsg": "An internal server error has occurred"
                      }
                    }
                  ]
                },
                "example": {
                  "errorCode": "internal_server_error",
                  "errorMsg": "An internal server error has occurred"
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": []
      }
    },
    "/v1/ekyc/{request_id}": {
      "get": {
        "summary": "Get details of eKYC Request",
        "operationId": "GetdetailsofaneKYCRequest",
        "parameters": [
          {
            "name": "request_id",
            "in": "path",
            "description": "ID (UUID4) of the create ekyc request",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{request_id}}"
            }
          },
          {
            "name": "x-client-id",
            "in": "header",
            "description": "Client id of the customer",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{client_id}}"
            }
          },
          {
            "name": "x-client-secret",
            "in": "header",
            "description": "Client secret of the customer",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{secret}}"
            }
          },
          {
            "name": "x-product-instance-id",
            "in": "header",
            "description": "Setu-ekyc product instance id",
            "required": true,
            "style": "simple",
            "schema": {
              "type": "string",
              "example": "{{x-product-instance-id}}"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/example1"
                    },
                    {
                      "example": {
                        "id": "0c624d3e-9cb0-4323-b468-d89092d7d305",
                        "status": "SUCCESS",
                        "kycURL": "http://localhost:3100/ekyc-web/0c624d3e-9cb0-4323-b468-d89092d7d305",
                        "data": {
                          "aadhaar": {
                            "name": "Ritesh Ujjwal",
                            "dateOfBirth": "1989",
                            "gender": "M",
                            "address": {
                              "careOf": "",
                              "country": "India",
                              "district": "ABC",
                              "house": "",
                              "landmark": "XYZ",
                              "locality": "AAAAAA",
                              "pin": "560001",
                              "postOffice": "Bangalore",
                              "state": "Karnataka",
                              "street": "ABC Road",
                              "subDistrict": "",
                              "vtc": "my location"
                            },
                            "photo": "...base64...",
                            "aadhaarNumber": "570003988888",
                            "generatedAt": "2024-03-22T15:18:35.269+05:30"
                          },
                          "xml": {
                            "xmlBase64": "...base64..."
                          }
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "id": "0c624d3e-9cb0-4323-b468-d89092d7d305",
                  "status": "SUCCESS",
                  "kycURL": "http://localhost:3100/ekyc-web/0c624d3e-9cb0-4323-b468-d89092d7d305",
                  "data": {
                    "aadhaar": {
                      "name": "Ritesh Ujjwal",
                      "dateOfBirth": "1989",
                      "gender": "M",
                      "address": {
                        "careOf": "",
                        "country": "India",
                        "district": "ABC",
                        "house": "",
                        "landmark": "XYZ",
                        "locality": "AAAAAA",
                        "pin": "560001",
                        "postOffice": "Bangalore",
                        "state": "Karnataka",
                        "street": "ABC Road",
                        "subDistrict": "",
                        "vtc": "my location"
                      },
                      "photo": "...base64...",
                      "aadhaarNumber": "570003988888",
                      "generatedAt": "2024-03-22T15:18:35.269+05:30"
                    },
                    "xml": {
                      "xmlBase64": "...base64..."
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "NOT FOUND",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/failure"
                    },
                    {
                      "example": {
                        "errorCode": "not_found",
                        "errorMsg": "eKYC id not found"
                      }
                    }
                  ]
                },
                "example": {
                  "errorCode": "not_found",
                  "errorMsg": "eKYC id not found"
                }
              }
            }
          },
          "500": {
            "description": "INTERNAL SERVER ERROR",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/failure"
                    },
                    {
                      "example": {
                        "errorCode": "internal_server_error",
                        "errorMsg": "An internal server error has occurred"
                      }
                    }
                  ]
                },
                "example": {
                  "errorCode": "internal_server_error",
                  "errorMsg": "An internal server error has occurred"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "success": {
        "title": "success",
        "required": ["id", "status", "kycUrl"],
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "ID (UUID4) of the eKYC request"
          },
          "status": {
            "type": "string",
            "description": "Status of the request",
            "enum": ["CREATED", "KYC_REQUESTED", "SUCCESS", "ERROR"]
          },
          "kycUrl": {
            "type": "string",
            "description": "URL to redirect the user for Aadhaar verification"
          }
        },
        "example": {
          "id": "0c624d3e-9cb0-4323-b468-d89092d7d305",
          "status": "CREATED",
          "kycUrl": "http://localhost:3100/ekyc-web/0c624d3e-9cb0-4323-b468-d89092d7d305"
        }
      },
      "failure": {
        "title": "failure",
        "required": ["errorCode", "errorMsg"],
        "type": "object",
        "properties": {
          "errorCode": {
            "type": "string",
            "description": "Error code"
          },
          "errorMsg": {
            "type": "string",
            "description": "Error message"
          }
        },
        "example": {
          "errorCode": "invalid_request",
          "errorMsg": "validation error: Field required"
        }
      },
      "example1": {
        "title": "example1",
        "required": ["id", "status", "kycURL", "data"],
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "description": "ID (UUID4) of the eKYC request"
          },
          "status": {
            "type": "string",
            "description": "Status of the request",
            "enum": ["CREATED", "KYC_REQUESTED", "SUCCESS", "ERROR"]
          },
          "kycURL": {
            "type": "string",
            "description": "URL to redirect the user for Aadhaar verification"
          },
          "data": {
            "$ref": "#/components/schemas/Data",
            "description": "eKYC data"
          }
        },
        "example": {
          "id": "0c624d3e-9cb0-4323-b468-d89092d7d305",
          "status": "SUCCESS",
          "kycURL": "http://localhost:3100/ekyc-web/0c624d3e-9cb0-4323-b468-d89092d7d305",
          "data": {
            "aadhaar": {
              "name": "Ritesh Ujjwal",
              "dateOfBirth": "1989",
              "gender": "M",
              "address": {
                "careOf": "",
                "country": "India",
                "district": "ABC",
                "house": "",
                "landmark": "XYZ",
                "locality": "AAAAAA",
                "pin": "560001",
                "postOffice": "Bangalore",
                "state": "Karnataka",
                "street": "ABC Road",
                "subDistrict": "",
                "vtc": "my location"
              },
              "photo": "...base64...",
              "aadhaarNumber": "570003988888",
              "generatedAt": "2024-03-22T15:18:35.269+05:30"
            },
            "xml": {
              "xmlBase64": "...base64..."
            }
          }
        }
      },
      "Data": {
        "title": "Data",
        "required": ["aadhaar", "xml"],
        "type": "object",
        "properties": {
          "aadhaar": {
            "$ref": "#/components/schemas/Aadhaar"
          },
          "xml": {
            "$ref": "#/components/schemas/Xml"
          }
        },
        "example": {
          "aadhaar": {
            "name": "Ritesh Ujjwal",
            "dateOfBirth": "1989",
            "gender": "M",
            "address": {
              "careOf": "",
              "country": "India",
              "district": "ABC",
              "house": "",
              "landmark": "XYZ",
              "locality": "AAAAAA",
              "pin": "560001",
              "postOffice": "Bangalore",
              "state": "Karnataka",
              "street": "ABC Road",
              "subDistrict": "",
              "vtc": "my location"
            },
            "photo": "...base64...",
            "aadhaarNumber": "570003988888",
            "generatedAt": "2024-03-22T15:18:35.269+05:30"
          },
          "xml": {
            "xmlBase64": "...base64..."
          }
        }
      },
      "Aadhaar": {
        "title": "Aadhaar",
        "required": [
          "name",
          "dateOfBirth",
          "gender",
          "address",
          "photo",
          "aadhaarNumber",
          "generatedAt"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "Name of the aadhaar holder"
          },
          "dateOfBirth": {
            "type": "string",
            "description": "Date of birth of the aadhaar holder"
          },
          "gender": {
            "type": "string",
            "description": "Gender of the aadhaar holder"
          },
          "address": {
            "$ref": "#/components/schemas/Address"
          },
          "photo": {
            "type": "string",
            "description": "Base64 encoded photo of the aadhaar holder"
          },
          "aadhaarNumber": {
            "type": "string",
            "description": "Masked aadhaar number of the aadhaar holder"
          },
          "generatedAt": {
            "type": "string",
            "description": "Timestamp when the eKYC data was generated"
          }
        },
        "example": {
          "name": "Ritesh Ujjwal",
          "dateOfBirth": "1989",
          "gender": "M",
          "address": {
            "careOf": "",
            "country": "India",
            "district": "ABC",
            "house": "",
            "landmark": "XYZ",
            "locality": "AAAAAA",
            "pin": "560001",
            "postOffice": "Bangalore",
            "state": "Karnataka",
            "street": "ABC Road",
            "subDistrict": "",
            "vtc": "my location"
          },
          "photo": "...base64...",
          "aadhaarNumber": "570003988888",
          "generatedAt": "2024-03-22T15:18:35.269+05:30"
        }
      },
      "Address": {
        "title": "Address",
        "required": [
          "careOf",
          "country",
          "district",
          "house",
          "landmark",
          "locality",
          "pin",
          "postOffice",
          "state",
          "street",
          "subDistrict",
          "vtc"
        ],
        "type": "object",
        "properties": {
          "careOf": {
            "type": "string",
            "description": "Name of the person the aadhaar holder is under care of (e.g., parent or guardian)"
          },
          "country": {
            "type": "string",
            "description": "Country where the aadhaar holder resides"
          },
          "district": {
            "type": "string",
            "description": "District in which the aadhaar holder resides"
          },
          "house": {
            "type": "string",
            "description": "House number or name where the aadhaar holder resides"
          },
          "landmark": {
            "type": "string",
            "description": "Nearby landmark for the aadhaar holder's address"
          },
          "locality": {
            "type": "string",
            "description": "Locality where the aadhaar holder resides"
          },
          "pin": {
            "type": "string",
            "description": "PIN code of the aadhaar holder's residence"
          },
          "postOffice": {
            "type": "string",
            "description": "Post office serving the aadhaar holder's locality"
          },
          "state": {
            "type": "string",
            "description": "State where the aadhaar holder resides"
          },
          "street": {
            "type": "string",
            "description": "Street name where the aadhaar holder resides"
          },
          "subDistrict": {
            "type": "string",
            "description": "Sub-district where the aadhaar holder resides"
          },
          "vtc": {
            "type": "string",
            "description": "Village, town or city where the aadhaar holder resides"
          }
        },
        "example": {
          "careOf": "",
          "country": "India",
          "district": "ABC",
          "house": "",
          "landmark": "XYZ",
          "locality": "AAAAAA",
          "pin": "560001",
          "postOffice": "Bangalore",
          "state": "Karnataka",
          "street": "ABC Road",
          "subDistrict": "",
          "vtc": "my location"
        }
      },
      "Xml": {
        "title": "Xml",
        "required": ["xmlBase64"],
        "type": "object",
        "properties": {
          "xmlBase64": {
            "type": "string",
            "description": "Base64 encoded XML data"
          }
        },
        "example": {
          "xmlBase64": "...base64..."
        }
      }
    }
  },
  "tags": []
}
