{
    "openapi": "3.0.0",
    "info": {
      "title": "Data Gateway - BAV Penny Less",
      "description": "Confirm the validity of an account from the account holderâ€™s bank, with penny-less drop done in real-time.",
      "contact": {},
      "version": "1.0"
    },
    "servers": [
        {
            "url": "https://dg-sandbox.setu.co",
            "description": "Sandbox"
        },
        {
            "url": "https://dg.setu.co",
            "description": "Production"
        }
    ],
    "paths": {
      "/pennyless": {
        "post": {
          "tags": [
            "PennyLess Drop"
          ],
          "summary": "Verify PennyLess Drop",
          "operationId": "VerifyPennyLessDrop",
          "parameters": [
            {
              "name": "x-client-id",
              "in": "header",
              "description": "",
              "required": true,
              "style": "simple",
              "schema": {
                "type": "string",
                "example": "{{client_id}}"
              }
            },
            {
              "name": "x-client-secret",
              "in": "header",
              "description": "",
              "required": true,
              "style": "simple",
              "schema": {
                "type": "string",
                "example": "{{secret}}"
              }
            },
            {
              "name": "x-product-instance-id",
              "in": "header",
              "description": "",
              "required": true,
              "style": "simple",
              "schema": {
                "type": "string",
                "example": "{{setu_bav_product_instance_id}}"
              }
            }
          ],
          "requestBody": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/VerifyPennyLessDropRequest"
                    },
                    {
                      "example": {
                        "accountNumber": "50100221813167",
                        "ifsc": "HDFC0000839"
                      }
                    }
                  ]
                },
                "example": {
                  "accountNumber": "50100221813167",
                  "ifsc": "HDFC0000839"
                }
              }
            },
            "required": true
          },
          "responses": {
            "200": {
              "description": "OK",
              "headers": {},
              "content": {
                "application/json": {
                  "schema": {
                    "allOf": [
                      {
                        "$ref": "#/components/schemas/VerifyPennyLessDropMerchant-Success"
                      },
                      {
                        "example": {
                          "traceId": "ca782918-f701-4033-84eb-30611381cfb7",
                          "data": {
                            "bankAccountNumber": "1234567890",
                            "bankAccountName": "Pavankumar Kamat Biz",
                            "bankAccountIfsc": "UTIB0002083",
                            "entityType": "MERCHANT",
                            "ifscCrossCheck": true,
                            "ifscDetails": {
                              "name": "Axis Bank",
                              "branch": "KAPODRA, SURAT",
                              "center": "SURAT",
                              "district": "SURAT",
                              "state": "GUJARAT",
                              "address": "J R SQUARE, MAMTA PARK - 1 KAPODRA, VARACHHA MAIN ROAD,  SURAT - 395 006",
                              "contact": "",
                              "imps": "true",
                              "rtgs": "true",
                              "city": "SURAT",
                              "iso3166": "IN-GJ",
                              "neft": "true",
                              "micr": "395211016",
                              "upi": "true",
                              "swift": ""
                            },
                            "merchantDetails": {
                              "mccCode": "1520",
                              "identifier": {
                                "merchantType": "SMALL",
                                "merchantGenre": "OFFLINE",
                                "onBoardingType": "BANK"
                              },
                              "name": {
                                "brand": "praimports",
                                "legal": "Indian",
                                "franchise": "rajababuimpor"
                              },
                              "ownership": {
                                "type": "PRIVATE"
                              }
                            }
                          },
                          "status": "SUCCESS"
                        }
                      }
                    ]
                  },
                  "example": {
                    "traceId": "ca782918-f701-4033-84eb-30611381cfb7",
                    "data": {
                      "bankAccountNumber": "1234567890",
                      "bankAccountName": "Pavankumar Kamat Biz",
                      "bankAccountIfsc": "UTIB0002083",
                      "entityType": "MERCHANT",
                      "ifscCrossCheck": true,
                      "ifscDetails": {
                        "name": "Axis Bank",
                        "branch": "KAPODRA, SURAT",
                        "center": "SURAT",
                        "district": "SURAT",
                        "state": "GUJARAT",
                        "address": "J R SQUARE, MAMTA PARK - 1 KAPODRA, VARACHHA MAIN ROAD,  SURAT - 395 006",
                        "contact": "",
                        "imps": "true",
                        "rtgs": "true",
                        "city": "SURAT",
                        "iso3166": "IN-GJ",
                        "neft": "true",
                        "micr": "395211016",
                        "upi": "true",
                        "swift": ""
                      },
                      "merchantDetails": {
                        "mccCode": "1520",
                        "identifier": {
                          "merchantType": "SMALL",
                          "merchantGenre": "OFFLINE",
                          "onBoardingType": "BANK"
                        },
                        "name": {
                          "brand": "praimports",
                          "legal": "Indian",
                          "franchise": "rajababuimpor"
                        },
                        "ownership": {
                          "type": "PRIVATE"
                        }
                      }
                    },
                    "status": "SUCCESS"
                  }
                }
              }
            },
            "500": {
              "description": "INTERNAL SERVER ERROR",
              "headers": {},
              "content": {
                "application/json": {
                  "schema": {
                    "allOf": [
                      {
                        "$ref": "#/components/schemas/VerifyPennyLessDrop-UpstreamError1"
                      },
                      {
                        "example": {
                          "error": {
                            "code": "upstream_service_error",
                            "detail": "Upstream service error. Please reach out to support along with the traceId.",
                            "traceId": "70541f30-0fb9-4ada-b197-3cfdf2ed1cda"
                          }
                        }
                      }
                    ]
                  },
                  "example": {
                    "error": {
                      "code": "upstream_service_error",
                      "detail": "Upstream service error. Please reach out to support along with the traceId.",
                      "traceId": "70541f30-0fb9-4ada-b197-3cfdf2ed1cda"
                    }
                  }
                }
              }
            },
            "400": {
              "description": "BAD REQUEST",
              "headers": {},
              "content": {
                "application/json": {
                  "schema": {
                    "allOf": [
                      {
                        "$ref": "#/components/schemas/VerifyPennyLessDrop-ValidationError1"
                      },
                      {
                        "example": {
                          "error": {
                            "code": "bad_request",
                            "detail": "accountNumber is required",
                            "traceId": "d039e5b4-1a06-45cb-9cc2-2d90933cdfeb"
                          }
                        }
                      }
                    ]
                  },
                  "example": {
                    "error": {
                      "code": "bad_request",
                      "detail": "accountNumber is required",
                      "traceId": "d039e5b4-1a06-45cb-9cc2-2d90933cdfeb"
                    }
                  }
                }
              }
            }
          },
          "deprecated": false,
          "security": []
        }
      }
    },
    "components": {
      "schemas": {
        "VerifyPennyLessDropRequest": {
          "title": "VerifyPennyLessDropRequest",
          "required": [
            "accountNumber",
            "ifsc"
          ],
          "type": "object",
          "properties": {
            "accountNumber": {
              "type": "string"
            },
            "ifsc": {
              "type": "string"
            }
          },
          "example": {
            "accountNumber": "50100221813167",
            "ifsc": "HDFC0000839"
          }
        },
        "VerifyPennyLessDropMerchant-Success": {
          "title": "VerifyPennyLessDropMerchant-Success",
          "required": [
            "traceId",
            "data",
            "status"
          ],
          "type": "object",
          "properties": {
            "traceId": {
              "type": "string"
            },
            "data": {
              "$ref": "#/components/schemas/Data"
            },
            "status": {
              "type": "string"
            }
          },
          "example": {
            "traceId": "ca782918-f701-4033-84eb-30611381cfb7",
            "data": {
              "bankAccountNumber": "1234567890",
              "bankAccountName": "Pavankumar Kamat Biz",
              "bankAccountIfsc": "UTIB0002083",
              "entityType": "MERCHANT",
              "ifscCrossCheck": true,
              "ifscDetails": {
                "name": "Axis Bank",
                "branch": "KAPODRA, SURAT",
                "center": "SURAT",
                "district": "SURAT",
                "state": "GUJARAT",
                "address": "J R SQUARE, MAMTA PARK - 1 KAPODRA, VARACHHA MAIN ROAD,  SURAT - 395 006",
                "contact": "",
                "imps": "true",
                "rtgs": "true",
                "city": "SURAT",
                "iso3166": "IN-GJ",
                "neft": "true",
                "micr": "395211016",
                "upi": "true",
                "swift": ""
              },
              "merchantDetails": {
                "mccCode": "1520",
                "identifier": {
                  "merchantType": "SMALL",
                  "merchantGenre": "OFFLINE",
                  "onBoardingType": "BANK"
                },
                "name": {
                  "brand": "praimports",
                  "legal": "Indian",
                  "franchise": "rajababuimpor"
                },
                "ownership": {
                  "type": "PRIVATE"
                }
              }
            },
            "status": "SUCCESS"
          }
        },
        "Data": {
          "title": "Data",
          "required": [
            "bankAccountNumber",
            "bankAccountName",
            "bankAccountIfsc",
            "entityType",
            "ifscCrossCheck",
            "ifscDetails",
            "merchantDetails"
          ],
          "type": "object",
          "properties": {
            "bankAccountNumber": {
              "type": "string"
            },
            "bankAccountName": {
              "type": "string"
            },
            "bankAccountIfsc": {
              "type": "string"
            },
            "entityType": {
              "type": "string"
            },
            "ifscCrossCheck": {
              "type": "boolean"
            },
            "ifscDetails": {
              "$ref": "#/components/schemas/IfscDetails"
            },
            "merchantDetails": {
              "$ref": "#/components/schemas/MerchantDetails"
            }
          },
          "example": {
            "bankAccountNumber": "1234567890",
            "bankAccountName": "Pavankumar Kamat Biz",
            "bankAccountIfsc": "UTIB0002083",
            "entityType": "MERCHANT",
            "ifscCrossCheck": true,
            "ifscDetails": {
              "name": "Axis Bank",
              "branch": "KAPODRA, SURAT",
              "center": "SURAT",
              "district": "SURAT",
              "state": "GUJARAT",
              "address": "J R SQUARE, MAMTA PARK - 1 KAPODRA, VARACHHA MAIN ROAD,  SURAT - 395 006",
              "contact": "",
              "imps": "true",
              "rtgs": "true",
              "city": "SURAT",
              "iso3166": "IN-GJ",
              "neft": "true",
              "micr": "395211016",
              "upi": "true",
              "swift": ""
            },
            "merchantDetails": {
              "mccCode": "1520",
              "identifier": {
                "merchantType": "SMALL",
                "merchantGenre": "OFFLINE",
                "onBoardingType": "BANK"
              },
              "name": {
                "brand": "praimports",
                "legal": "Indian",
                "franchise": "rajababuimpor"
              },
              "ownership": {
                "type": "PRIVATE"
              }
            }
          }
        },
        "IfscDetails": {
          "title": "IfscDetails",
          "required": [
            "name",
            "branch",
            "center",
            "district",
            "state",
            "address",
            "contact",
            "imps",
            "rtgs",
            "city",
            "iso3166",
            "neft",
            "micr",
            "upi",
            "swift"
          ],
          "type": "object",
          "properties": {
            "name": {
              "type": "string"
            },
            "branch": {
              "type": "string"
            },
            "center": {
              "type": "string"
            },
            "district": {
              "type": "string"
            },
            "state": {
              "type": "string"
            },
            "address": {
              "type": "string"
            },
            "contact": {
              "type": "string"
            },
            "imps": {
              "type": "string"
            },
            "rtgs": {
              "type": "string"
            },
            "city": {
              "type": "string"
            },
            "iso3166": {
              "type": "string"
            },
            "neft": {
              "type": "string"
            },
            "micr": {
              "type": "string"
            },
            "upi": {
              "type": "string"
            },
            "swift": {
              "type": "string"
            }
          },
          "example": {
            "name": "Axis Bank",
            "branch": "KAPODRA, SURAT",
            "center": "SURAT",
            "district": "SURAT",
            "state": "GUJARAT",
            "address": "J R SQUARE, MAMTA PARK - 1 KAPODRA, VARACHHA MAIN ROAD,  SURAT - 395 006",
            "contact": "",
            "imps": "true",
            "rtgs": "true",
            "city": "SURAT",
            "iso3166": "IN-GJ",
            "neft": "true",
            "micr": "395211016",
            "upi": "true",
            "swift": ""
          }
        },
        "MerchantDetails": {
          "title": "MerchantDetails",
          "required": [
            "mccCode",
            "identifier",
            "name",
            "ownership"
          ],
          "type": "object",
          "properties": {
            "mccCode": {
              "type": "string"
            },
            "identifier": {
              "$ref": "#/components/schemas/Identifier"
            },
            "name": {
              "$ref": "#/components/schemas/Name"
            },
            "ownership": {
              "$ref": "#/components/schemas/Ownership"
            }
          },
          "example": {
            "mccCode": "1520",
            "identifier": {
              "merchantType": "SMALL",
              "merchantGenre": "OFFLINE",
              "onBoardingType": "BANK"
            },
            "name": {
              "brand": "praimports",
              "legal": "Indian",
              "franchise": "rajababuimpor"
            },
            "ownership": {
              "type": "PRIVATE"
            }
          }
        },
        "Identifier": {
          "title": "Identifier",
          "required": [
            "merchantType",
            "merchantGenre",
            "onBoardingType"
          ],
          "type": "object",
          "properties": {
            "merchantType": {
              "type": "string"
            },
            "merchantGenre": {
              "type": "string"
            },
            "onBoardingType": {
              "type": "string"
            }
          },
          "example": {
            "merchantType": "SMALL",
            "merchantGenre": "OFFLINE",
            "onBoardingType": "BANK"
          }
        },
        "Name": {
          "title": "Name",
          "required": [
            "brand",
            "legal",
            "franchise"
          ],
          "type": "object",
          "properties": {
            "brand": {
              "type": "string"
            },
            "legal": {
              "type": "string"
            },
            "franchise": {
              "type": "string"
            }
          },
          "example": {
            "brand": "praimports",
            "legal": "Indian",
            "franchise": "rajababuimpor"
          }
        },
        "Ownership": {
          "title": "Ownership",
          "required": [
            "type"
          ],
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            }
          },
          "example": {
            "type": "PRIVATE"
          }
        },
        "VerifyPennyLessDropIndividual-Success": {
          "title": "VerifyPennyLessDropIndividual-Success",
          "required": [
            "traceId",
            "data",
            "status"
          ],
          "type": "object",
          "properties": {
            "traceId": {
              "type": "string"
            },
            "data": {
              "$ref": "#/components/schemas/Data1"
            },
            "status": {
              "type": "string"
            }
          },
          "example": {
            "traceId": "d0cc92a4-ca3f-4eb8-bbeb-4126620ec844",
            "data": {
              "bankAccountNumber": "1234567891",
              "bankAccountName": "Pavankumar Kamat",
              "bankAccountIfsc": "UTIB0002083",
              "entityType": "INDIVIDUAL",
              "ifscCrossCheck": true,
              "ifscDetails": {
                "name": "Axis Bank",
                "branch": "KAPODRA, SURAT",
                "center": "SURAT",
                "district": "SURAT",
                "state": "GUJARAT",
                "address": "J R SQUARE, MAMTA PARK - 1 KAPODRA, VARACHHA MAIN ROAD,  SURAT - 395 006",
                "contact": "",
                "imps": "true",
                "rtgs": "true",
                "city": "SURAT",
                "iso3166": "IN-GJ",
                "neft": "true",
                "micr": "395211016",
                "upi": "true",
                "swift": ""
              }
            },
            "status": "SUCCESS"
          }
        },
        "Data1": {
          "title": "Data1",
          "required": [
            "bankAccountNumber",
            "bankAccountName",
            "bankAccountIfsc",
            "entityType",
            "ifscCrossCheck",
            "ifscDetails"
          ],
          "type": "object",
          "properties": {
            "bankAccountNumber": {
              "type": "string"
            },
            "bankAccountName": {
              "type": "string"
            },
            "bankAccountIfsc": {
              "type": "string"
            },
            "entityType": {
              "type": "string"
            },
            "ifscCrossCheck": {
              "type": "boolean"
            },
            "ifscDetails": {
              "$ref": "#/components/schemas/IfscDetails"
            }
          },
          "example": {
            "bankAccountNumber": "1234567891",
            "bankAccountName": "Pavankumar Kamat",
            "bankAccountIfsc": "UTIB0002083",
            "entityType": "INDIVIDUAL",
            "ifscCrossCheck": true,
            "ifscDetails": {
              "name": "Axis Bank",
              "branch": "KAPODRA, SURAT",
              "center": "SURAT",
              "district": "SURAT",
              "state": "GUJARAT",
              "address": "J R SQUARE, MAMTA PARK - 1 KAPODRA, VARACHHA MAIN ROAD,  SURAT - 395 006",
              "contact": "",
              "imps": "true",
              "rtgs": "true",
              "city": "SURAT",
              "iso3166": "IN-GJ",
              "neft": "true",
              "micr": "395211016",
              "upi": "true",
              "swift": ""
            }
          }
        },
        "VerifyPennyLessDrop-InvalidBankdetails": {
          "title": "VerifyPennyLessDrop-InvalidBankdetails",
          "required": [
            "traceId",
            "message",
            "status"
          ],
          "type": "object",
          "properties": {
            "traceId": {
              "type": "string"
            },
            "message": {
              "type": "string"
            },
            "status": {
              "type": "string"
            }
          },
          "example": {
            "traceId": "bda7cd75-a145-4138-82ad-257555501ed5",
            "message": "Invalid bank details",
            "status": "ERROR"
          }
        },
        "Error": {
          "title": "Error",
          "required": [
            "code",
            "detail",
            "traceId"
          ],
          "type": "object",
          "properties": {
            "code": {
              "type": "string"
            },
            "detail": {
              "type": "string"
            },
            "traceId": {
              "type": "string"
            }
          },
          "example": {
            "code": "upstream_service_error",
            "detail": "Upstream service error. Please reach out to support along with the traceId.",
            "traceId": "70541f30-0fb9-4ada-b197-3cfdf2ed1cda"
          }
        },
        "VerifyPennyLessDrop-UpstreamError1": {
          "title": "VerifyPennyLessDrop-UpstreamError1",
          "required": [
            "error"
          ],
          "type": "object",
          "properties": {
            "error": {
              "$ref": "#/components/schemas/Error"
            }
          },
          "example": {
            "error": {
              "code": "upstream_service_error",
              "detail": "Upstream service error. Please reach out to support along with the traceId.",
              "traceId": "70541f30-0fb9-4ada-b197-3cfdf2ed1cda"
            }
          }
        },
        "VerifyPennyLessDrop-ValidationError1": {
          "title": "VerifyPennyLessDrop-ValidationError1",
          "required": [
            "error"
          ],
          "type": "object",
          "properties": {
            "error": {
              "$ref": "#/components/schemas/Error"
            }
          },
          "example": {
            "error": {
              "code": "bad_request",
              "detail": "accountNumber is required",
              "traceId": "d039e5b4-1a06-45cb-9cc2-2d90933cdfeb"
            }
          }
        }
      },
      "securitySchemes": {
        "bearer": {
          "type": "http",
          "scheme": "bearer"
        }
      }
    },
    "security": [
      {
        "bearer": []
      }
    ],
    "tags": [
      {
        "name": "PennyLess Drop"
      }
    ]
  }